// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
